name = "NormalizingFlowFilters"
uuid = "bdff3154-b03d-49d9-ae6e-73db1909c910"
authors = ["Grant Bruer gbruer15@gmail.com and contributors"]
version = "0.0.1"

[deps]
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ImageQualityIndexes = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
InvertibleNetworks = "b7115f24-5f92-4794-81e8-23b0ddb121d3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Configurations = "0.17.6"
Flux = "0.13.17,0.14.20"
InvertibleNetworks = "2.3.0"
ImageQualityIndexes = "0.3.7"
LinearAlgebra = "1.10"
LogExpFunctions = "0.3.28"
MLUtils = "0.4.4"
Random = "1.10"
Statistics = "1.10"
julia = "1.10"
