[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NormalizingFlowFilters = "bdff3154-b03d-49d9-ae6e-73db1909c910"
PairPlots = "43a3c2be-4208-490b-832a-a21dcd55d7da"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestReports = "dcd651b4-b50a-5b6b-8f22-87e9f253a252"
